# Generated by Django 3.2.3 on 2021-05-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0002_alter_exeat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exeat',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Disproved'), ('AD', 'Awaiting Dean Approval'),
                                            ('AE', 'Awaiting Acceptance')], default='P', max_length=2),
        ),
    ]
