# Generated by Django 3.2.3 on 2021-05-20 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0003_alter_exeat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeat',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='approval',
            name='dsa_approval',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accept'), ('RJ', 'Reject')], default='PE',
                                   max_length=2),
        ),
        migrations.AlterField(
            model_name='approval',
            name='exeat_team_acceptance',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accept'), ('RJ', 'Reject')], default='PE',
                                   max_length=2),
        ),
    ]
