# Generated by Django 3.2.3 on 2021-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0004_auto_20210520_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='clocked_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='clocked_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
