# Generated by Django 3.2.3 on 2021-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0005_auto_20210520_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exeat',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Disproved'), ('AD', 'Awaiting Dean Approval'),
                                            ('AE', 'Awaiting Acceptance'), ('A', 'Approved')], default='P',
                                   max_length=2),
        ),
    ]
