# Generated by Django 3.2.3 on 2021-05-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210524_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exeatextension',
            name='previous_return',
        ),
        migrations.AlterField(
            model_name='exeat',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/%Y%m%d'),
        ),
    ]
