# Generated by Django 3.2.3 on 2021-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210529_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeat',
            name='disapproval_reason',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
