# Generated by Django 3.2.3 on 2021-05-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210529_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeatextension',
            name='Reason',
            field=models.CharField(default='ha', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exeatextension',
            name='approval',
            field=models.CharField(choices=[('P', 'Pending'), ('AC', 'Accept'), ('RJ', 'Reject')], default='P', max_length=2),
        ),
    ]
