# Generated by Django 3.2.3 on 2021-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210529_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeatextension',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/%Y%m%d'),
        ),
    ]
