# Generated by Django 3.2.3 on 2021-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_exeatextension_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Program',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='New', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='New', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exeat',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Disapproved'), ('AD', 'Awaiting Dean Approval'), ('AE', 'Awaiting Acceptance'), ('A', 'Approved')], default='P', max_length=2),
        ),
    ]
